### PR TITLE
[#WIP] Reformating, Code Performance.

### LINKED ISSUE #1: TO-DO List
Fixes:
 - Brewing Stands
 - Hoppers
 - Enchanting Table (Just need to show an Inventory)

Implement:
 - Nether
 - All the stuff on "leveryl.yml"

### LINKED ISSUE #2: New Blocks
Add all the new 1.1 blocks

### LINKED ISSUE #90: Certain Players crash my server here's the crash dump
```
Leveryl Crash Dump Sat Jul 29 11:42:10 CDT 2017

Error: Argument 1 passed to pocketmine\utils\BinaryStream::putUUID() must be an instance of pocketmine\utils\UUID, null given, called in /home/customer/NormalFac/src/pocketmine/network/mcpe/protocol/AddPlayerPacket.php on line 70
File: /src/pocketmine/utils/BinaryStream
Line: 285
Type: notice

Code:
[276] 		//This is actually two little-endian longs: UUID Most followed by UUID Least
[277] 		$part1 = $this->getLInt();
[278] 		$part0 = $this->getLInt();
[279] 		$part3 = $this->getLInt();
[280] 		$part2 = $this->getLInt();
[281] 
[282] 		return new UUID($part0, $part1, $part2, $part3);
[283] 	}
[284] 
[285] 	public function putUUID(UUID $uuid)
[286] 	{
[287] 		$this->putLInt($uuid->getPart(1));
[288] 		$this->putLInt($uuid->getPart(0));
[289] 		$this->putLInt($uuid->getPart(3));
[290] 		$this->putLInt($uuid->getPart(2));
[291] 	}
[292] 
[293] 	public function getSlot(): Item
[294] 	{
[295] 		$id = $this->getVarInt();

Backtrace:
#0 /src/pocketmine/network/mcpe/protocol/AddPlayerPacket(70): pocketmine\utils\BinaryStream->putUUID(NULL )
#1 /src/pocketmine/network/mcpe/RakLibInterface(219): pocketmine\network\mcpe\protocol\AddPlayerPacket->encode()
#2 /src/pocketmine/Player(1206): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\AddPlayerPacket object, boolean , boolean )
#3 /src/pocketmine/entity/Wolf(56): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\AddPlayerPacket object)
#4 /src/pocketmine/Player(942): pocketmine\entity\Wolf->spawnTo(pocketmine\Player object)
#5 /src/pocketmine/level/Level(1496): pocketmine\Player->sendChunk(integer -44, integer -78, pocketmine\network\mcpe\protocol\BatchPacket object)
#6 /src/pocketmine/level/Level(2921): pocketmine\level\Level->sendChunkFromCache(integer -44, integer -78)
#7 /src/pocketmine/level/format/io/ChunkRequestTask(96): pocketmine\level\Level->chunkRequestCallback(integer -44, integer -78, pocketmine\network\mcpe\protocol\BatchPacket object)
#8 /src/pocketmine/scheduler/AsyncPool(170): pocketmine\level\format\io\ChunkRequestTask->onCompletion(pocketmine\Server object)
#9 /src/pocketmine/scheduler/ServerScheduler(367): pocketmine\scheduler\AsyncPool->collectTasks()
#10 /src/pocketmine/Server(2683): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 26685)
#11 /src/pocketmine/Server(2434): pocketmine\Server->tick()
#12 /src/pocketmine/Server(2310): pocketmine\Server->tickProcessor()
#13 /src/pocketmine/Server(1846): pocketmine\Server->start()
#14 /src/pocketmine/PocketMine(510): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/customer/NormalFac/, string /home/customer/NormalFac/, string /home/customer/NormalFac/plugins/)

Leveryl version: 1.0 #0 [Protocol 113; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux s107071 3.13.0-116-generic #163-Ubuntu SMP Fri Mar 31 14:13:22 UTC 2017 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux
```

### PR DESCRIPTION
**Pull request by ghost**
## Introduction
This PR is created for more Performance on Code and fix Fucking Formating.

[!] Updates:
1) Add more Packets and Fix these Packets. ~ 100% 
2) Fix Formating on Network Folder ~ 100%
3) Fix Formating on Blocks Folder ~ 0%
4) Fix Formating on Command Folder ~ 0%
5) Fix Formating on Entity Folder ~ 0%
6) Fix Formating on Event Folder ~ 0%
7) Fix Formating on Inventory Folder ~ 0%
8) Fix Formating on Item Folder ~ 0%
9) Fix Formating on Lang Folder ~ 0%
10) Fix Formating on Level Folder ~ 0%
11) Fix Formating on Math Folder ~ 0%
12) Fix Formating on Metadata Folder ~ 0%
13) Fix Formating on NBT Folder ~ 0%
14) Fix Formating on Network Folder ~ 0%
15) Fix Formating on Permission Folder ~ 0%
16) Fix Formating on Plugin Folder ~ 0%
17) Fix Formating on ResourcePack Folder ~ 0%
18) Fix Formating on Resources Folder ~ 0%
19) Fix Formating on Scheduler Folder ~ 0%
20) Fix Formating on Tile Folder ~ 0%
21) Fix Formating on Utils Folder ~ 0%
22) Fix Formating on Wizard Folder ~ 0%
23) Fix ALL Formating. ~ 0%

### Relevant issues
List relevant issues here (If there's any.)
* Trying fix #90 

## Follow-up
Suggest any actions to be done before/after merging this pull request

## Tests
Attach scripts or actions to test this pull request's stability, as well as the result

### CODE REVIEW

**Comment by ghost** [comment]
1) Add more Packets and Fix these Packets. ~ 100%  

Now need fix reformat.

@CortexPE Can you help me?

**Comment by CortexPE** [comment]
sure

**Comment by CortexPE** [comment]
don't cancel the CI tests...

**Comment by DerddyDert** [comment]
Awesome

**Comment by ghost** [comment]
@CortexPE I'm watched to all files and you reformated code, correctly?

**Comment by CortexPE** [comment]
needs tests

**Pull request merged**
