### PR TITLE
Update Player.php

### PR DESCRIPTION
**Pull request by yesitswalid**
Fixed offset 0 Player.php + Fixed inventory win 10

## Introduction
Offset 0 + Fixed Inventory Win 10

### Relevant issues
* Fixed Error Offset: 0 
* Fixed Inventory for the window 10 Player.

## Follow-up
Tested work fine.

## Tests
https://github.com/wiligangster/Leveryl/commit/aeea2f7630ba8a52a22603309bf10c19ebcca7c5

### CODE REVIEW

**Comment by CortexPE** [comment]
How did you test this?

**Comment by yesitswalid** [comment]
Yep, I test and everything works ;)

**Comment by CortexPE** [comment]
I mean, How?
specific crafting recipe or video so I can compare with and without the PR

**Comment by CortexPE** [comment]
Untested for almost a month.

**Pull request closed without merging**
