### PR TITLE
[RE-OPENED] Update Packets and Fix Formatting

### PR DESCRIPTION
**Pull request by CortexPE**
## Introduction
Update Packets and Fix Formatting

### Relevant issues
List relevant issues here (If there's any.)
* Fixes Issues regarding Packets and Restores PocketMine Style Formatting

### CODE REVIEW

**Comment by ghost** [comment]
@CortexPE Lolll, why you revented? :o

**Comment by ghost** [comment]
Ok ,this PR is so buggy and branch bugged....

Where is all changes? ⭕️

**Comment by CortexPE** [comment]
Welp. You should've just merged the PR when you were done xd
I reverted it because it bugged so much... :/
I reopened it here because the PR is merged and there's no actual way of re-opening the PR (except with this method)

**Comment by ghost** [comment]
@CortexPE I don't know how fix enter ... pmmp changed all methods of enter on server and Leveryl is outdated... 

If you fix, i continue, sorry.

**Comment by CortexPE** [comment]
ok
but we dont have to be EXACTLY PMMP....

**Comment by junkdude** [comment]
all he does is copy and paste...

**Comment by ghost** [comment]
@junkdude Lol, it's copy-paste latest packets for work enter . Formating is by me -_-

**Pull request closed without merging**
