### PR TITLE
Added event\server\ServerShutdownEvent from Tesseract.

### LINKED ISSUE #1: TO-DO List
Fixes:
 - Brewing Stands
 - Hoppers
 - Enchanting Table (Just need to show an Inventory)

Implement:
 - Nether
 - All the stuff on "leveryl.yml"

### LINKED ISSUE #2: New Blocks
Add all the new 1.1 blocks

### PR DESCRIPTION
**Pull request by RoyalMCPE**
## Introduction
Ported the ServerShutdownEvent from Tesseract

### Relevant issues
None

## Follow-up
None.

## Tests
Transfer a player to a different once the event is called.

### CODE REVIEW

**Comment by CortexPE** [comment]
Please fix the PR first. :)

**Review by junkdude — COMMENTED** [review]
generally looks good, havent tested yet

**Comment by CortexPE** [comment]
You don't need to edit StopCommand.

**Review by CortexPE — CHANGES_REQUESTED** [review]
Don't need to edit StopCommand,
You only need to call ServerShutdownEvent on shutdown()... Other lines are unnecessary.

**Review by CortexPE — APPROVED** [review]

**Comment by CortexPE** [comment]
So many errors. LOL

**Pull request merged**
