### PR TITLE
Korean Configuration Files

### PR DESCRIPTION
**Pull request by shdudwns**
leveryl_kor.yml add please

### CODE REVIEW

**Comment by shdudwns** [comment]
@CortexPE add please leveryl_kor.yml

**Comment by shdudwns** [comment]
Finish!
@CortexPE upload

**Comment by shdudwns** [comment]
Please put the file
Lerveryl_kor.yml and pockmine_kor.yml

**Comment by CortexPE** [comment]
dude u removed the original pocketmine.yml lol

**Comment by shdudwns** [comment]
@CortexPE why??

**Comment by shdudwns** [comment]
I added pocketmine
Please copy the yml code copy.
@CortexPE

**Comment by shdudwns** [comment]
finish!

**Pull request merged**
